"""empty message

Revision ID: f6d9535c1f50
Revises: ea8256ab66f2
Create Date: 2024-05-03 18:24:19.262332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6d9535c1f50'
down_revision = 'ea8256ab66f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite_vehicles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vehicles_name', sa.Integer(), nullable=True))
        batch_op.drop_constraint('favorite_vehicles_vehicles_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'vehicles', ['vehicles_name'], ['name'])
        batch_op.drop_column('vehicles_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite_vehicles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vehicles_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('favorite_vehicles_vehicles_id_fkey', 'vehicles', ['vehicles_id'], ['id'])
        batch_op.drop_column('vehicles_name')

    # ### end Alembic commands ###
